# Generated by Django 4.2.9 on 2026-09-15 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_quizquestion_question_type_and_more'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='authorizer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='authorizer_position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course_name',
            field=models.CharField(blank=True, default='', help_text='Course title on certificate (snapshot).', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/issued_logos/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization_name',
            field=models.CharField(default='Global Professional Institute', help_text='Organization name (snapshot).', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/issued_signatures/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], db_index=True, default='ISSUED', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student_name',
            field=models.CharField(blank=True, default='', help_text='Student display name on certificate (snapshot).', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template_id',
            field=models.CharField(choices=[('template_1', 'Academic Prestige'), ('template_2', 'Professional Classic'), ('template_3', 'Modern Minimal'), ('template_4', 'Premium Corporate')], default='template_1', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseCertificateConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='When true, eligible students receive certificates automatically.')),
                ('template_id', models.CharField(choices=[('template_1', 'Academic Prestige'), ('template_2', 'Professional Classic'), ('template_3', 'Modern Minimal'), ('template_4', 'Premium Corporate')], default='template_1', help_text='Selected certificate design template.', max_length=50)),
                ('organization_name', models.CharField(default='Global Professional Institute', help_text='Organization / Institution name printed on certificate.', max_length=255)),
                ('logo_image', models.ImageField(blank=True, help_text='Custom logo for certificate. Defaults to site logo if empty.', null=True, upload_to='certificates/logos/')),
                ('authorizer_name', models.CharField(blank=True, default='', help_text='Name of the authorizer / signatory.', max_length=255)),
                ('authorizer_position', models.CharField(blank=True, default='Director', help_text='Title / position of the authorizer.', max_length=255)),
                ('signature_image', models.ImageField(blank=True, help_text='Authorized signature image.', null=True, upload_to='certificates/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_config', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_certificate_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Certificate Configuration',
                'verbose_name_plural': 'Course Certificate Configurations',
                'db_table': 'course_certificate_configs',
            },
        ),
    ]
