# Generated by Django 4.2.9 on 2026-09-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_certificate_authorizer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='logo_size',
            field=models.PositiveIntegerField(default=100, help_text='Logo scale percentage (snapshot).'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_size',
            field=models.PositiveIntegerField(default=100, help_text='Signature scale percentage (snapshot).'),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='logo_size',
            field=models.PositiveIntegerField(default=100, help_text='Custom logo size percentage (default 100).'),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='signature_size',
            field=models.PositiveIntegerField(default=100, help_text='Custom signature size percentage (default 100).'),
        ),
    ]
