# Generated by Django 4.2.9 on 2026-09-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_certificate_logo_size_certificate_signature_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='additional_authorizer_name',
            field=models.CharField(blank=True, default='', help_text='Additional authorizer display name on certificate (snapshot).', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='additional_authorizer_position',
            field=models.CharField(blank=True, default='', help_text='Additional authorizer position on certificate (snapshot).', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='additional_signature_image',
            field=models.ImageField(blank=True, help_text='Additional authorized signature image (snapshot).', null=True, upload_to='certificates/issued_signatures/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='additional_signature_size',
            field=models.PositiveIntegerField(default=100, help_text='Additional signature scale percentage (snapshot).'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enable_additional_authorizer',
            field=models.BooleanField(default=False, help_text='Whether additional authorizer was enabled at time of issuance (snapshot).'),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='additional_authorizer_name',
            field=models.CharField(blank=True, default='', help_text='Name of the additional authorizer / signatory.', max_length=255),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='additional_authorizer_position',
            field=models.CharField(blank=True, default='', help_text='Title / position of the additional authorizer.', max_length=255),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='additional_signature_image',
            field=models.ImageField(blank=True, help_text='Additional authorized signature image.', null=True, upload_to='certificates/signatures/'),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='additional_signature_size',
            field=models.PositiveIntegerField(default=100, help_text='Additional signature scale percentage (default 100).'),
        ),
        migrations.AddField(
            model_name='coursecertificateconfig',
            name='enable_additional_authorizer',
            field=models.BooleanField(default=False, help_text='When true, displays an additional authorizer & signature on the certificate.'),
        ),
    ]
