# Generated by Django 4.2.9 on 2026-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_certificate_additional_authorizer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='template_id',
            field=models.CharField(choices=[('template_1', 'Academic Prestige'), ('template_2', 'Professional Classic'), ('template_3', 'Modern Minimal'), ('template_4', 'Premium Corporate'), ('template_5', 'Participation')], default='template_1', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursecertificateconfig',
            name='template_id',
            field=models.CharField(choices=[('template_1', 'Academic Prestige'), ('template_2', 'Professional Classic'), ('template_3', 'Modern Minimal'), ('template_4', 'Premium Corporate'), ('template_5', 'Participation')], default='template_1', help_text='Selected certificate design template.', max_length=50),
        ),
    ]
