# Generated by Django 4.2.9 on 2026-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_add_participation_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='employee_id',
            field=models.CharField(blank=True, default='', help_text='Student employee ID on certificate (snapshot).', max_length=100),
        ),
    ]
