# Generated by Django 4.2.9 on 2026-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='who_can_join',
            field=models.TextField(blank=True, help_text='Who can join this course'),
        ),
    ]
