# Generated by Django 4.2.9 on 2026-02-11 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_who_can_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admission_deadline',
            field=models.DateField(blank=True, help_text='Last date for admission', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='available_seats',
            field=models.PositiveIntegerField(default=30, help_text='Number of seats currently available'),
        ),
        migrations.AddField(
            model_name='course',
            name='class_starts',
            field=models.DateField(blank=True, help_text='Date when classes start', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.TextField(blank=True, help_text='e.g., Saturday, Monday, Wednesday - 6:30PM to 9:00PM'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_seats',
            field=models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='venue',
            field=models.CharField(blank=True, help_text='Class venue/location', max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['class_starts'], name='courses_class_s_c6bcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['admission_deadline'], name='courses_admissi_7945bd_idx'),
        ),
    ]
