# Generated by Django 4.2.9 on 2026-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_admission_deadline_course_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('LIVE', 'Live'), ('TEXT', 'Text/Article'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('RESOURCE', 'Resource/Download')], default='VIDEO', max_length=20),
        ),
    ]
