# Generated by Django 4.2.9 on 2026-03-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_classes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of classes/sessions'),
        ),
    ]
