# Generated by Django 4.2.9 on 2026-04-06 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_total_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats currently available'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_seats',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of students allowed', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
