# Generated by Django 4.2.9 on 2026-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='delivery_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BOTH', 'Both Online & Offline')], default='ONLINE', help_text='Is this course online, offline, or both?', max_length=20),
        ),
    ]
