# Generated by Django 4.2.9 on 2026-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marked as completed by instructor'),
        ),
    ]
