# Generated by Django 4.2.9 on 2026-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='disqualification_reason',
            field=models.CharField(blank=True, choices=[('excessive_warnings', 'Excessive Warnings'), ('manual', 'Manual Override'), ('time_expired', 'Time Expired')], max_length=50),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='shuffled_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['is_disqualified'], name='quiz_submis_is_disq_a6300a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsubmission',
            index=models.Index(fields=['warnings_count'], name='quiz_submis_warning_86e3da_idx'),
        ),
    ]
