# Generated by Django 4.2.9 on 2026-08-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_quizsubmission_disqualification_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing the announcement', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing the announcement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
