# Generated by Django 4.2.9 on 2026-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_quiz_expires_at_quizsubmission_student_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='student_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
