# Generated by Django 4.2.9 on 2026-09-02 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_quizsubmission_student_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Course price in BDT (0 for free)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
