# Generated by Django 4.2.9 on 2026-09-17 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0016_quizquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coordinators',
            field=models.ManyToManyField(blank=True, help_text='Additional instructors assigned as course coordinators', limit_choices_to={'role': 'INSTRUCTOR'}, related_name='coordinated_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
