# Generated by Django 4.2.9 on 2026-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_merchant_number', models.CharField(default='01XXXXXXXXX', help_text='The bKash merchant number students should pay to.', max_length=20)),
                ('bkash_qr_code', models.ImageField(blank=True, help_text='Upload the bKash QR code image.', null=True, upload_to='settings/payment/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
