# Generated by Django 4.2.9 on 2026-08-02 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTickerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('color', models.CharField(default='bg-[#3B5EF5]', help_text='Tailwind background color class for the ticker bullet', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing the ticker item', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing the ticker item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_ticker_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
