# Generated by Django 4.2.9 on 2026-08-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newstickeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstickeritem',
            name='link',
            field=models.URLField(blank=True, help_text='Optional URL to open when the ticker item is clicked.', max_length=500, null=True),
        ),
    ]
