# Generated by Django 4.2.9 on 2026-08-28 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_newstickeritem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('SMS_STUDENT_VERIFICATION', 'SMS - Student Verification'), ('SMS_COURSE_APPROVAL', 'SMS - Course Purchase Approval'), ('SMS_QUIZ_RESULT_PASS', 'SMS - Quiz Result (Pass)'), ('SMS_QUIZ_RESULT_FAIL', 'SMS - Quiz Result (Fail)'), ('EMAIL_STUDENT_VERIFICATION', 'Email - Student Verification'), ('EMAIL_COURSE_PURCHASE', 'Email - Course Purchase Confirmation'), ('EMAIL_COURSE_APPROVAL', 'Email - Course Approval Confirmation'), ('EMAIL_INSTRUCTOR_ANNOUNCEMENT', 'Email - Instructor Announcement'), ('EMAIL_ADMIN_ANNOUNCEMENT', 'Email - Admin Announcement'), ('EMAIL_COURSE_COMPLETION', 'Email - Course Completion Confirmation')], db_index=True, max_length=50, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, help_text='Email Subject line (ignored for SMS)', max_length=255)),
                ('template_body', models.TextField(help_text='Body content with variables like [Student Name], [Course Name], [Score], etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='greenweb_sms_token',
            field=models.CharField(blank=True, help_text='Token for Greenweb BD SMS API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quiz_pass_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Passing score percentage for quizzes (e.g. 40, 50, 60)', max_digits=5),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], db_index=True, max_length=10)),
                ('notification_type', models.CharField(choices=[('SMS_STUDENT_VERIFICATION', 'SMS - Student Verification'), ('SMS_COURSE_APPROVAL', 'SMS - Course Purchase Approval'), ('SMS_QUIZ_RESULT_PASS', 'SMS - Quiz Result (Pass)'), ('SMS_QUIZ_RESULT_FAIL', 'SMS - Quiz Result (Fail)'), ('EMAIL_STUDENT_VERIFICATION', 'Email - Student Verification'), ('EMAIL_COURSE_PURCHASE', 'Email - Course Purchase Confirmation'), ('EMAIL_COURSE_APPROVAL', 'Email - Course Approval Confirmation'), ('EMAIL_INSTRUCTOR_ANNOUNCEMENT', 'Email - Instructor Announcement'), ('EMAIL_ADMIN_ANNOUNCEMENT', 'Email - Admin Announcement'), ('EMAIL_COURSE_COMPLETION', 'Email - Course Completion Confirmation')], db_index=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='SENT', max_length=20)),
                ('response_data', models.TextField(blank=True, help_text='API response or error stack')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
