# Generated by Django 4.2.9 on 2026-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificationtemplate_sitesettings_greenweb_sms_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='campus_tour_heading',
            field=models.CharField(blank=True, default='Virtual Campus Tour', help_text="Custom heading for the video card. Defaults to 'Virtual Campus Tour' if empty.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='campus_tour_subtext',
            field=models.CharField(blank=True, default='Experience our state-of-the-art facilities', help_text="Custom subtext for the video card. Defaults to 'Experience our state-of-the-art facilities' if empty.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='campus_tour_thumbnail',
            field=models.ImageField(blank=True, help_text='Optional custom thumbnail for the video card.', null=True, upload_to='settings/videos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='campus_tour_video',
            field=models.FileField(blank=True, help_text='Upload a video file for the Virtual Campus Tour on the homepage.', null=True, upload_to='settings/videos/'),
        ),
    ]
