# Generated by Django 4.2.9 on 2026-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_campus_tour_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('SMS_REGISTRATION_VERIFICATION', 'SMS - Registration Verification Link'), ('SMS_STUDENT_VERIFICATION', 'SMS - Student Verification'), ('SMS_COURSE_APPROVAL', 'SMS - Course Purchase Approval'), ('SMS_QUIZ_RESULT_PASS', 'SMS - Quiz Result (Pass)'), ('SMS_QUIZ_RESULT_FAIL', 'SMS - Quiz Result (Fail)'), ('EMAIL_STUDENT_VERIFICATION', 'Email - Student Verification'), ('EMAIL_COURSE_PURCHASE', 'Email - Course Purchase Confirmation'), ('EMAIL_COURSE_APPROVAL', 'Email - Course Approval Confirmation'), ('EMAIL_INSTRUCTOR_ANNOUNCEMENT', 'Email - Instructor Announcement'), ('EMAIL_ADMIN_ANNOUNCEMENT', 'Email - Admin Announcement'), ('EMAIL_COURSE_COMPLETION', 'Email - Course Completion Confirmation')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.CharField(choices=[('SMS_REGISTRATION_VERIFICATION', 'SMS - Registration Verification Link'), ('SMS_STUDENT_VERIFICATION', 'SMS - Student Verification'), ('SMS_COURSE_APPROVAL', 'SMS - Course Purchase Approval'), ('SMS_QUIZ_RESULT_PASS', 'SMS - Quiz Result (Pass)'), ('SMS_QUIZ_RESULT_FAIL', 'SMS - Quiz Result (Fail)'), ('EMAIL_STUDENT_VERIFICATION', 'Email - Student Verification'), ('EMAIL_COURSE_PURCHASE', 'Email - Course Purchase Confirmation'), ('EMAIL_COURSE_APPROVAL', 'Email - Course Approval Confirmation'), ('EMAIL_INSTRUCTOR_ANNOUNCEMENT', 'Email - Instructor Announcement'), ('EMAIL_ADMIN_ANNOUNCEMENT', 'Email - Admin Announcement'), ('EMAIL_COURSE_COMPLETION', 'Email - Course Completion Confirmation')], db_index=True, max_length=50, unique=True),
        ),
    ]
