# Generated by Django 4.2.9 on 2026-09-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_notificationlog_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='album_heading',
            field=models.CharField(blank=True, default='Campus & Event Gallery', help_text='Custom heading for the Photo Album card in About section.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='album_subtext',
            field=models.CharField(blank=True, default='Explore our vibrant campus life, workshops, and student achievements', help_text='Custom subtext for the Photo Album card.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Short title or caption for the photo', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional longer description')),
                ('image', models.ImageField(help_text='Uploaded album photo file', upload_to='album/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this photo from the public album')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album Photo',
                'verbose_name_plural': 'Album Photos',
                'db_table': 'album_photos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
