/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useEffect, useState, useRef } from 'react'
import { useLocation, useNavigate, Link } from 'react-router-dom'
import {
    Settings,
    Save,
    QrCode,
    Phone,
    Upload,
    Image as ImageIcon,
    CheckCircle2,
    AlertCircle,
    Info,
    Video,
    Film,
    Play,
    Sparkles,
    Camera,
    Loader2,
    Images,
    Trash2,
    Eye,
    EyeOff,
    ArrowUp,
    ArrowDown,
    Plus,
    Edit3,
    X,
    Check,
    CreditCard,
    Bell,
    ChevronRight,
    LayoutGrid,
} from 'lucide-react'
import {
    getSiteSettings,
    updateSiteSettings,
    getAlbumPhotos,
    batchUploadAlbumPhotos,
    updateAlbumPhoto,
    deleteAlbumPhoto,
    reorderAlbumPhotos,
    getMediaUrl,
} from '../../../../lib/api'
import type { SiteSettings, AlbumPhoto } from '../../../../types'
import SEO from '../../../components/SEO'
import { toast } from 'react-hot-toast'
import { isAxiosError } from 'axios'

type TabType = 'overview' | 'video' | 'album' | 'payment' | 'notifications'
type SavingSection = 'video' | 'album' | 'bkash' | 'quiz' | null

const SiteSettingsPage: React.FC = () => {
    const location = useLocation()
    const navigate = useNavigate()

    // Determine current active sub-menu tab from URL path
    const getActiveTabFromPath = (): TabType => {
        const path = location.pathname
        if (path.endsWith('/video')) return 'video'
        if (path.endsWith('/album')) return 'album'
        if (path.endsWith('/payment')) return 'payment'
        if (path.endsWith('/notifications')) return 'notifications'
        return 'overview'
    }

    const activeTab = getActiveTabFromPath()

    const [settings, setSettings] = useState<SiteSettings | null>(null)
    const [loading, setLoading] = useState(true)
    const [savingSection, setSavingSection] = useState<SavingSection>(null)

    // Form state - Homepage Video Tour
    const [videoHeading, setVideoHeading] = useState('')
    const [videoSubtext, setVideoSubtext] = useState('')
    const [videoFile, setVideoFile] = useState<File | null>(null)
    const [videoPreviewUrl, setVideoPreviewUrl] = useState<string | null>(null)
    const [thumbnailFile, setThumbnailFile] = useState<File | null>(null)
    const [thumbnailPreviewUrl, setThumbnailPreviewUrl] = useState<string | null>(null)
    const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false)
    const [isAutoGeneratedThumb, setIsAutoGeneratedThumb] = useState(false)

    // Form state - Photo Album (About Section)
    const [albumHeading, setAlbumHeading] = useState('')
    const [albumSubtext, setAlbumSubtext] = useState('')
    const [albumPhotos, setAlbumPhotos] = useState<AlbumPhoto[]>([])
    const [loadingPhotos, setLoadingPhotos] = useState(false)
    const [selectedUploadFiles, setSelectedUploadFiles] = useState<File[]>([])
    const [uploadTitlePrefix, setUploadTitlePrefix] = useState('')
    const [uploadCaption, setUploadCaption] = useState('')
    const [isUploadingPhotos, setIsUploadingPhotos] = useState(false)
    const [editingPhotoId, setEditingPhotoId] = useState<string | null>(null)
    const [editTitle, setEditTitle] = useState('')
    const [editCaption, setEditCaption] = useState('')

    // Form state - bKash
    const [merchantNumber, setMerchantNumber] = useState('')
    const [qrCodeFile, setQrCodeFile] = useState<File | null>(null)
    const [qrCodePreview, setQrCodePreview] = useState<string | null>(null)

    // Form state - Quiz & SMS
    const [quizPassPercentage, setQuizPassPercentage] = useState<number>(50)
    const [greenwebSmsToken, setGreenwebSmsToken] = useState('')

    const videoPreviewRef = useRef<HTMLVideoElement | null>(null)

    useEffect(() => {
        fetchSettings()
        fetchPhotos()
    }, [])

    const fetchSettings = async () => {
        try {
            const response = await getSiteSettings()
            if (response?.data?.success) {
                const data = response.data.data
                setSettings(data)
                // Video settings
                setVideoHeading(data.campus_tour_heading || '')
                setVideoSubtext(data.campus_tour_subtext || '')
                setVideoPreviewUrl(data.campus_tour_video || null)
                setThumbnailPreviewUrl(data.campus_tour_thumbnail || null)
                // Album settings
                setAlbumHeading(data.album_heading || '')
                setAlbumSubtext(data.album_subtext || '')
                // bKash settings
                setMerchantNumber(data.bkash_merchant_number || '')
                setQrCodePreview(data.bkash_qr_code)
                // Quiz & SMS settings
                setQuizPassPercentage(data.quiz_pass_percentage ?? 50)
                setGreenwebSmsToken(data.greenweb_sms_token || '')
            }
        } catch (error: any) {
            toast.error(error.message || 'Failed to load settings')
        } finally {
            setLoading(false)
        }
    }

    const fetchPhotos = async () => {
        setLoadingPhotos(true)
        try {
            const res = await getAlbumPhotos()
            const resData: any = res?.data
            let list: AlbumPhoto[] = []
            if (Array.isArray(resData)) {
                list = resData
            } else if (resData?.data && Array.isArray(resData.data)) {
                list = resData.data
            } else if (resData?.results && Array.isArray(resData.results)) {
                list = resData.results
            }
            setAlbumPhotos(list)
        } catch (err) {
            console.error('Failed to load album photos', err)
        } finally {
            setLoadingPhotos(false)
        }
    }

    const generateThumbnailFromVideo = (file: File): Promise<File> => {
        return new Promise((resolve, reject) => {
            const video = document.createElement('video')
            video.preload = 'auto'
            video.muted = true
            video.playsInline = true
            const objectUrl = URL.createObjectURL(file)
            video.src = objectUrl

            video.onloadeddata = () => {
                const seekTime = Math.min(1.0, video.duration > 1 ? 1.0 : video.duration / 2 || 0.1)
                video.currentTime = seekTime
            }

            video.onseeked = () => {
                try {
                    const canvas = document.createElement('canvas')
                    canvas.width = video.videoWidth || 1280
                    canvas.height = video.videoHeight || 720
                    const ctx = canvas.getContext('2d')
                    if (ctx) {
                        ctx.drawImage(video, 0, 0, canvas.width, canvas.height)
                        canvas.toBlob((blob) => {
                            URL.revokeObjectURL(objectUrl)
                            if (blob) {
                                const cleanName = file.name.replace(/\.[^/.]+$/, '')
                                const thumbFile = new File([blob], `thumb_${cleanName}.jpg`, {
                                    type: 'image/jpeg',
                                })
                                resolve(thumbFile)
                            } else {
                                reject(new Error('Failed to generate thumbnail blob'))
                            }
                        }, 'image/jpeg', 0.90)
                    } else {
                        URL.revokeObjectURL(objectUrl)
                        reject(new Error('Canvas 2D context not available'))
                    }
                } catch (err) {
                    URL.revokeObjectURL(objectUrl)
                    reject(err)
                }
            }

            video.onerror = (e) => {
                URL.revokeObjectURL(objectUrl)
                reject(e)
            }
        })
    }

    const handleCaptureCurrentFrame = () => {
        if (!videoPreviewRef.current) return
        const video = videoPreviewRef.current
        try {
            const canvas = document.createElement('canvas')
            canvas.width = video.videoWidth || 1280
            canvas.height = video.videoHeight || 720
            const ctx = canvas.getContext('2d')
            if (ctx) {
                ctx.drawImage(video, 0, 0, canvas.width, canvas.height)
                canvas.toBlob((blob) => {
                    if (blob) {
                        const thumbFile = new File([blob], `captured_frame_${Date.now()}.jpg`, {
                            type: 'image/jpeg',
                        })
                        setThumbnailFile(thumbFile)
                        setThumbnailPreviewUrl(URL.createObjectURL(thumbFile))
                        setIsAutoGeneratedThumb(true)
                        toast.success('Captured current video frame as thumbnail!')
                    }
                }, 'image/jpeg', 0.92)
            }
        } catch (err) {
            console.error('Frame capture error:', err)
            toast.error('Could not capture frame from current video')
        }
    }

    const handleVideoFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            if (file.size > 200 * 1024 * 1024) {
                toast.error('Video file size should not exceed 200MB')
                return
            }
            setVideoFile(file)
            setVideoPreviewUrl(URL.createObjectURL(file))

            setIsGeneratingThumbnail(true)
            try {
                const autoThumb = await generateThumbnailFromVideo(file)
                setThumbnailFile(autoThumb)
                setThumbnailPreviewUrl(URL.createObjectURL(autoThumb))
                setIsAutoGeneratedThumb(true)
                toast.success('Auto-generated video thumbnail from first frame!')
            } catch (err) {
                console.warn('Auto thumbnail generation warning:', err)
            } finally {
                setIsGeneratingThumbnail(false)
            }
        }
    }

    const handleThumbnailFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            setThumbnailFile(file)
            setIsAutoGeneratedThumb(false)
            const reader = new FileReader()
            reader.onloadend = () => {
                setThumbnailPreviewUrl(reader.result as string)
            }
            reader.readAsDataURL(file)
        }
    }

    const handleQrCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            setQrCodeFile(file)
            const reader = new FileReader()
            reader.onloadend = () => {
                setQrCodePreview(reader.result as string)
            }
            reader.readAsDataURL(file)
        }
    }

    // ── Save Video Section ──────────────────────────────────────────────────
    const handleSaveVideo = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('video')

        try {
            const formData = new FormData()
            formData.append('campus_tour_heading', videoHeading)
            formData.append('campus_tour_subtext', videoSubtext)

            if (videoFile) {
                formData.append('campus_tour_video', videoFile)
            }
            if (thumbnailFile) {
                formData.append('campus_tour_thumbnail', thumbnailFile)
            }

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('Homepage video settings saved successfully!')
                const updated = response.data.data
                setSettings(updated)
                setVideoFile(null)
                setThumbnailFile(null)
                setVideoPreviewUrl(updated.campus_tour_video || null)
                setThumbnailPreviewUrl(updated.campus_tour_thumbnail || null)
                setIsAutoGeneratedThumb(false)
            }
        } catch (error) {
            let message = 'Failed to save video settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    // ── Save Album Section Heading & Subtext ────────────────────────────────
    const handleSaveAlbumSettings = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('album')

        try {
            const formData = new FormData()
            formData.append('album_heading', albumHeading)
            formData.append('album_subtext', albumSubtext)

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('Album title and subtext saved successfully!')
                setSettings(response.data.data)
            }
        } catch (error) {
            let message = 'Failed to save album settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    // ── Multi-Photo Upload Handlers ─────────────────────────────────────────
    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = Array.from(e.target.files || [])
        if (files.length > 0) {
            setSelectedUploadFiles((prev) => [...prev, ...files])
        }
    }

    const handleRemoveSelectedFile = (index: number) => {
        setSelectedUploadFiles((prev) => prev.filter((_, idx) => idx !== index))
    }

    const handleBatchUpload = async () => {
        if (selectedUploadFiles.length === 0) return

        setIsUploadingPhotos(true)
        try {
            const formData = new FormData()
            selectedUploadFiles.forEach((file) => {
                formData.append('images', file)
            })
            if (uploadTitlePrefix.trim()) {
                formData.append('title_prefix', uploadTitlePrefix.trim())
            }
            if (uploadCaption.trim()) {
                formData.append('caption', uploadCaption.trim())
            }

            const res = await batchUploadAlbumPhotos(formData)
            if (res.data.success) {
                toast.success(`Successfully uploaded ${selectedUploadFiles.length} photo(s)!`)
                setSelectedUploadFiles([])
                setUploadTitlePrefix('')
                setUploadCaption('')
                fetchPhotos()
            }
        } catch (err: any) {
            toast.error(err?.response?.data?.error?.message || 'Failed to upload photos')
        } finally {
            setIsUploadingPhotos(false)
        }
    }

    // ── Photo Item Management Handlers ─────────────────────────────────────
    const handleTogglePhotoVisibility = async (photo: AlbumPhoto) => {
        try {
            const res = await updateAlbumPhoto(photo.id, { is_active: !photo.is_active })
            if (res.data.success) {
                setAlbumPhotos((prev) =>
                    prev.map((p) => (p.id === photo.id ? { ...p, is_active: !photo.is_active } : p))
                )
                toast.success(photo.is_active ? 'Photo hidden from homepage' : 'Photo set visible on homepage')
            }
        } catch (err) {
            toast.error('Failed to update photo visibility')
        }
    }

    const handleDeletePhoto = async (photoId: string) => {
        if (!window.confirm('Are you sure you want to delete this photo from the album?')) {
            return
        }

        try {
            const res = await deleteAlbumPhoto(photoId)
            if (res.data.success) {
                setAlbumPhotos((prev) => prev.filter((p) => p.id !== photoId))
                toast.success('Photo removed from album')
            }
        } catch (err) {
            toast.error('Failed to delete photo')
        }
    }

    const handleMovePhoto = async (index: number, direction: 'up' | 'down') => {
        const targetIndex = direction === 'up' ? index - 1 : index + 1
        if (targetIndex < 0 || targetIndex >= albumPhotos.length) return

        const reordered = [...albumPhotos]
        const temp = reordered[index]
        reordered[index] = reordered[targetIndex]
        reordered[targetIndex] = temp

        setAlbumPhotos(reordered)

        const orders = reordered.map((item, idx) => ({
            id: item.id,
            order: idx + 1,
        }))

        try {
            await reorderAlbumPhotos(orders)
            toast.success('Photo sequence updated!')
        } catch (err) {
            toast.error('Failed to save new order')
            fetchPhotos()
        }
    }

    const handleStartEdit = (photo: AlbumPhoto) => {
        setEditingPhotoId(photo.id)
        setEditTitle(photo.title || '')
        setEditCaption(photo.caption || '')
    }

    const handleSaveEdit = async (photoId: string) => {
        try {
            const res = await updateAlbumPhoto(photoId, {
                title: editTitle,
                caption: editCaption,
            })
            if (res.data.success) {
                setAlbumPhotos((prev) =>
                    prev.map((p) =>
                        p.id === photoId ? { ...p, title: editTitle, caption: editCaption } : p
                    )
                )
                setEditingPhotoId(null)
                toast.success('Photo details updated!')
            }
        } catch (err) {
            toast.error('Failed to update photo details')
        }
    }

    // ── Save bKash Section ──────────────────────────────────────────────────
    const handleSaveBkash = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('bkash')

        try {
            const formData = new FormData()
            formData.append('bkash_merchant_number', merchantNumber)

            if (qrCodeFile) {
                formData.append('bkash_qr_code', qrCodeFile)
            }

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('bKash payment settings saved successfully!')
                const updated = response.data.data
                setSettings(updated)
                setQrCodeFile(null)
                setQrCodePreview(updated.bkash_qr_code)
            }
        } catch (error) {
            let message = 'Failed to save bKash settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    // ── Save Quiz & SMS Section ─────────────────────────────────────────────
    const handleSaveQuiz = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('quiz')

        try {
            const formData = new FormData()
            formData.append('quiz_pass_percentage', quizPassPercentage.toString())
            formData.append('greenweb_sms_token', greenwebSmsToken)

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('Quiz & SMS notification settings saved successfully!')
                const updated = response.data.data
                setSettings(updated)
            }
        } catch (error) {
            let message = 'Failed to save quiz settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    // Navigation sub-menu tabs definitions
    const navTabs = [
        {
            id: 'overview',
            label: 'Overview',
            path: '/dashboard/admin/settings',
            icon: LayoutGrid,
            count: null,
            badgeColor: 'bg-gray-100 text-gray-700',
        },
        {
            id: 'video',
            label: 'Homepage Video',
            path: '/dashboard/admin/settings/video',
            icon: Video,
            count: videoPreviewUrl ? 'Active' : 'Empty',
            badgeColor: videoPreviewUrl ? 'bg-indigo-50 text-indigo-700 border border-indigo-200' : 'bg-gray-100 text-gray-500',
        },
        {
            id: 'album',
            label: 'Photo Album',
            path: '/dashboard/admin/settings/album',
            icon: Images,
            count: `${albumPhotos.length}`,
            badgeColor: 'bg-emerald-50 text-emerald-700 border border-emerald-200',
        },
        {
            id: 'payment',
            label: 'Payment Details',
            path: '/dashboard/admin/settings/payment',
            icon: CreditCard,
            count: merchantNumber ? 'bKash' : null,
            badgeColor: 'bg-pink-50 text-pink-700 border border-pink-200',
        },
        {
            id: 'notifications',
            label: 'Quiz & Notifications',
            path: '/dashboard/admin/settings/notifications',
            icon: Bell,
            count: `${quizPassPercentage}%`,
            badgeColor: 'bg-violet-50 text-violet-700 border border-violet-200',
        },
    ]

    const getTabTitle = () => {
        switch (activeTab) {
            case 'video':
                return { name: 'Homepage Video Tour', subtitle: 'Configure hero section video tour, custom thumbnails, and headline captions' }
            case 'album':
                return { name: 'Photo Album & Gallery', subtitle: 'Upload and organize showcase photos displayed in the homepage About section' }
            case 'payment':
                return { name: 'Payment Details (bKash)', subtitle: 'Manage merchant bKash number and QR code for checkout payments' }
            case 'notifications':
                return { name: 'Quiz & SMS Settings', subtitle: 'Set passing marks and configure Greenweb SMS gateway integration' }
            default:
                return { name: 'Platform Settings', subtitle: 'Centralized configuration for website media, payment gateways, and platform settings' }
        }
    }

    const { name: pageTitle } = getTabTitle()

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-100">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
            </div>
        )
    }

    return (
        <div className="py-6 px-4 md:px-6">
            <SEO title={`${pageTitle} | Admin Dashboard`} noindex={true} />
            <div className="mb-6">
                <h1 className="text-xl font-semibold text-gray-900 tracking-tight">{pageTitle}</h1>
                <p className="text-sm text-gray-400 mt-0.5">Manage Easily manage your homepage interactive video tour, event photo album, student payment details, and automated quiz evaluation from the sub-menus below. .</p>
            </div>

            {/* ── Modern Sub-Menu Horizontal Tabs Navigation Bar ── */}
            <div className="mb-8 border-b border-gray-200/80 bg-white rounded-2xl p-2 shadow-xs">
                <div className="flex items-center gap-1.5 overflow-x-auto scrollbar-none">
                    {navTabs.map((tab) => {
                        const Icon = tab.icon
                        const isCurrent = activeTab === tab.id
                        return (
                            <Link
                                key={tab.id}
                                to={tab.path}
                                className={`flex items-center gap-2.5 px-4 py-2.5 rounded-xl text-xs md:text-sm font-semibold transition-all duration-200 whitespace-nowrap shrink-0 cursor-pointer ${isCurrent
                                    ? 'bg-gray-900 text-white shadow-md'
                                    : 'text-gray-600 hover:text-gray-900 hover:bg-gray-100/80'
                                    }`}
                            >
                                <Icon className={`w-4 h-4 ${isCurrent ? 'text-white' : 'text-gray-500'}`} />
                                <span>{tab.label}</span>
                                {tab.count !== null && (
                                    <span
                                        className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${isCurrent
                                            ? 'bg-white/20 text-white'
                                            : tab.badgeColor
                                            }`}
                                    >
                                        {tab.count}
                                    </span>
                                )}
                            </Link>
                        )
                    })}
                </div>
            </div>

            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* ── TAB 1: OVERVIEW & DASHBOARD SUMMARY ─────────────────────────── */}
            {/* ─────────────────────────────────────────────────────────────────── */}
            {activeTab === 'overview' && (
                <div className="space-y-8 animate-in fade-in duration-200">
                    {/* Quick Access Function Cards Grid */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* 1. Homepage Video Card */}
                        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-all flex flex-col justify-between group">
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <div className="w-12 h-12 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center text-indigo-600">
                                        <Video className="w-6 h-6" />
                                    </div>
                                    <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-indigo-50 text-indigo-700 border border-indigo-200">
                                        Hero Section
                                    </span>
                                </div>
                                <div>
                                    <h3 className="text-base font-bold text-gray-900 group-hover:text-indigo-600 transition-colors">
                                        Homepage Video Tour
                                    </h3>
                                    <p className="text-xs text-gray-500 mt-1 leading-relaxed">
                                        Upload virtual campus tour video, auto-extract video thumbnails, and customize hero section captions.
                                    </p>
                                </div>
                                <div className="pt-2 text-xs text-gray-600 bg-gray-50 p-3 rounded-xl">
                                    <p className="font-semibold text-gray-800 truncate">Title: {videoHeading || 'Virtual Campus Tour'}</p>
                                    <p className="text-gray-400 truncate mt-0.5">{videoSubtext || 'Experience our state-of-the-art facilities'}</p>
                                </div>
                            </div>

                            <div className="pt-6 mt-4 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-gray-400 font-medium">Sub-menu: Video</span>
                                <button
                                    type="button"
                                    onClick={() => navigate('/dashboard/admin/settings/video')}
                                    className="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold shadow-sm transition-all cursor-pointer"
                                >
                                    Manage Video <ChevronRight className="w-3.5 h-3.5" />
                                </button>
                            </div>
                        </div>

                        {/* 2. Photo Album Card */}
                        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-all flex flex-col justify-between group">
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <div className="w-12 h-12 rounded-2xl bg-emerald-50 border border-emerald-100 flex items-center justify-center text-emerald-600">
                                        <Images className="w-6 h-6" />
                                    </div>
                                    <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">
                                        {albumPhotos.length} Photos ({albumPhotos.filter((p) => p.is_active).length} Active)
                                    </span>
                                </div>
                                <div>
                                    <h3 className="text-base font-bold text-gray-900 group-hover:text-emerald-600 transition-colors">
                                        Photo Album & Canvas Gallery
                                    </h3>
                                    <p className="text-xs text-gray-500 mt-1 leading-relaxed">
                                        Batch upload high-res photos, drag & reorder sequence, edit titles, and power the homepage interactive canvas viewer.
                                    </p>
                                </div>
                                <div className="pt-2 text-xs text-gray-600 bg-gray-50 p-3 rounded-xl flex items-center justify-between">
                                    <span className="font-semibold text-gray-800">Heading: {albumHeading || 'Campus & Event Gallery'}</span>
                                    <span className="text-emerald-700 font-bold">{albumPhotos.length} Uploaded</span>
                                </div>
                            </div>

                            <div className="pt-6 mt-4 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-gray-400 font-medium">Sub-menu: Photo Album</span>
                                <button
                                    type="button"
                                    onClick={() => navigate('/dashboard/admin/settings/album')}
                                    className="inline-flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold shadow-sm transition-all cursor-pointer"
                                >
                                    Manage Album <ChevronRight className="w-3.5 h-3.5" />
                                </button>
                            </div>
                        </div>

                        {/* 3. bKash Payment Gateway Card */}
                        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-all flex flex-col justify-between group">
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <div className="w-12 h-12 rounded-2xl bg-pink-50 border border-pink-100 flex items-center justify-center text-[#D12053]">
                                        <CreditCard className="w-6 h-6" />
                                    </div>
                                    <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-pink-50 text-pink-700 border border-pink-200">
                                        Checkout Gateway
                                    </span>
                                </div>
                                <div>
                                    <h3 className="text-base font-bold text-gray-900 group-hover:text-pink-600 transition-colors">
                                        bKash Payment Details
                                    </h3>
                                    <p className="text-xs text-gray-500 mt-1 leading-relaxed">
                                        Configure official merchant account number and dynamic QR code image displayed on the student checkout screen.
                                    </p>
                                </div>
                                <div className="pt-2 text-xs text-gray-600 bg-gray-50 p-3 rounded-xl flex items-center justify-between font-mono">
                                    <span className="font-bold text-gray-900">{merchantNumber || 'No number set'}</span>
                                    <span className="text-xs font-sans text-pink-600 font-semibold">{qrCodePreview ? 'QR Uploaded' : 'No QR'}</span>
                                </div>
                            </div>

                            <div className="pt-6 mt-4 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-gray-400 font-medium">Sub-menu: Payment</span>
                                <button
                                    type="button"
                                    onClick={() => navigate('/dashboard/admin/settings/payment')}
                                    className="inline-flex items-center gap-1.5 px-4 py-2 bg-[#D12053] hover:bg-[#b01742] text-white rounded-xl text-xs font-bold shadow-sm transition-all cursor-pointer"
                                >
                                    Configure bKash <ChevronRight className="w-3.5 h-3.5" />
                                </button>
                            </div>
                        </div>

                        {/* 4. Quiz & Notification Card */}
                        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-all flex flex-col justify-between group">
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <div className="w-12 h-12 rounded-2xl bg-violet-50 border border-violet-100 flex items-center justify-center text-violet-600">
                                        <Bell className="w-6 h-6" />
                                    </div>
                                    <span className="text-xs font-bold px-2.5 py-1 rounded-full bg-violet-50 text-violet-700 border border-violet-200">
                                        Pass Mark: {quizPassPercentage}%
                                    </span>
                                </div>
                                <div>
                                    <h3 className="text-base font-bold text-gray-900 group-hover:text-violet-600 transition-colors">
                                        Quiz & SMS Notifications
                                    </h3>
                                    <p className="text-xs text-gray-500 mt-1 leading-relaxed">
                                        Configure quiz passing criteria and integrate Greenweb Bangladesh SMS gateway for automated SMS triggers.
                                    </p>
                                </div>
                                <div className="pt-2 text-xs text-gray-600 bg-gray-50 p-3 rounded-xl flex items-center justify-between">
                                    <span>Greenweb SMS: <strong className="text-violet-700">{greenwebSmsToken ? 'Token Configured' : 'Not Connected'}</strong></span>
                                    <span className="font-bold">{quizPassPercentage}% Score</span>
                                </div>
                            </div>

                            <div className="pt-6 mt-4 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-gray-400 font-medium">Sub-menu: Notifications</span>
                                <button
                                    type="button"
                                    onClick={() => navigate('/dashboard/admin/settings/notifications')}
                                    className="inline-flex items-center gap-1.5 px-4 py-2 bg-violet-600 hover:bg-violet-700 text-white rounded-xl text-xs font-bold shadow-sm transition-all cursor-pointer"
                                >
                                    Configure SMS & Quiz <ChevronRight className="w-3.5 h-3.5" />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* ── TAB 2: HOMEPAGE VIDEO TOUR SUB-MENU ─────────────────────────── */}
            {/* ─────────────────────────────────────────────────────────────────── */}
            {activeTab === 'video' && (
                <div className="max-w-4xl space-y-6 animate-in fade-in duration-200">
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                        <div className="bg-linear-to-r from-blue-50 to-indigo-50 px-6 py-4 border-b border-blue-100 flex items-center justify-between">
                            <div className="flex items-center">
                                <Video className="w-5 h-5 text-indigo-600 mr-3" />
                                <div>
                                    <h2 className="text-base font-bold text-gray-800">Virtual Campus Tour Video</h2>
                                    <p className="text-xs text-gray-500">Displayed in the Hero Section right column on the public homepage</p>
                                </div>
                            </div>
                            <span className="text-xs text-indigo-600 font-semibold bg-white px-2.5 py-1 rounded-lg border border-indigo-100">
                                Hero Section Media
                            </span>
                        </div>

                        <form onSubmit={handleSaveVideo}>
                            <div className="p-6 sm:p-8 space-y-6">
                                {/* Heading & Subtext */}
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-xs font-bold text-gray-700 mb-2">
                                            Video Heading
                                        </label>
                                        <input
                                            type="text"
                                            value={videoHeading}
                                            onChange={(e) => setVideoHeading(e.target.value)}
                                            placeholder="Virtual Campus Tour"
                                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white focus:border-transparent transition-all outline-none text-sm text-gray-800"
                                        />
                                        <p className="text-[11px] text-gray-400 mt-1">
                                            Leave empty to use: <strong>"Virtual Campus Tour"</strong>
                                        </p>
                                    </div>

                                    <div>
                                        <label className="block text-xs font-bold text-gray-700 mb-2">
                                            Video Subtext
                                        </label>
                                        <input
                                            type="text"
                                            value={videoSubtext}
                                            onChange={(e) => setVideoSubtext(e.target.value)}
                                            placeholder="Experience our state-of-the-art facilities"
                                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white focus:border-transparent transition-all outline-none text-sm text-gray-800"
                                        />
                                        <p className="text-[11px] text-gray-400 mt-1">
                                            Leave empty to use: <strong>"Experience our state-of-the-art facilities"</strong>
                                        </p>
                                    </div>
                                </div>

                                {/* Video File Upload & Live Preview */}
                                <div>
                                    <label className="block text-xs font-bold text-gray-700 mb-2 flex items-center gap-2">
                                        <Film className="w-4 h-4 text-indigo-500" />
                                        Campus Tour Video File (.mp4, .webm, .mov)
                                    </label>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
                                        {/* Video Preview */}
                                        <div className="w-full h-52 bg-gray-900 rounded-2xl overflow-hidden relative flex flex-col items-center justify-center border border-gray-200 group">
                                            {videoPreviewUrl ? (
                                                <>
                                                    <video
                                                        ref={videoPreviewRef}
                                                        src={getMediaUrl(videoPreviewUrl)}
                                                        controls
                                                        className="w-full h-full object-contain"
                                                        poster={thumbnailPreviewUrl ? getMediaUrl(thumbnailPreviewUrl) : undefined}
                                                    />
                                                    <button
                                                        type="button"
                                                        onClick={handleCaptureCurrentFrame}
                                                        title="Capture current paused video frame as thumbnail"
                                                        className="absolute top-3 right-3 px-2.5 py-1.5 bg-black/70 hover:bg-black/90 text-white rounded-lg text-xs font-semibold backdrop-blur-sm border border-white/20 transition-all flex items-center gap-1.5 cursor-pointer opacity-0 group-hover:opacity-100 z-10"
                                                    >
                                                        <Camera className="w-3.5 h-3.5" /> Capture Frame
                                                    </button>
                                                </>
                                            ) : (
                                                <div className="text-center p-4">
                                                    <Play className="w-10 h-10 text-gray-600 mx-auto mb-2" />
                                                    <p className="text-xs text-gray-400 font-medium">No Custom Video Uploaded</p>
                                                    <p className="text-[10px] text-gray-500 mt-0.5">Placeholder modal is active on homepage</p>
                                                </div>
                                            )}
                                        </div>

                                        {/* Upload Controls & Extraction Help */}
                                        <div className="space-y-3">
                                            <div className="bg-indigo-50/70 p-4 rounded-xl border border-indigo-100 text-xs text-indigo-900 space-y-1">
                                                <p className="font-bold flex items-center gap-1.5">
                                                    <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                                                    Smart Thumbnail Extractor:
                                                </p>
                                                <p className="text-[11px] opacity-90">
                                                    Selecting a new video file will automatically generate a crisp poster thumbnail from the initial video frame.
                                                </p>
                                            </div>

                                            <div className="flex flex-col gap-2">
                                                <label className="inline-flex items-center px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-xs font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-all cursor-pointer shadow-sm w-fit">
                                                    <Upload className="w-3.5 h-3.5 mr-2 text-indigo-600" />
                                                    {videoPreviewUrl ? 'Replace Video File' : 'Select Video File'}
                                                    <input
                                                        type="file"
                                                        className="hidden"
                                                        onChange={handleVideoFileChange}
                                                        accept="video/*"
                                                    />
                                                </label>

                                                {isGeneratingThumbnail && (
                                                    <span className="text-xs text-indigo-600 font-medium flex items-center gap-1.5">
                                                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                                                        Extracting thumbnail...
                                                    </span>
                                                )}

                                                {videoFile && (
                                                    <span className="text-xs text-green-600 font-medium flex items-center gap-1">
                                                        <CheckCircle2 className="w-3.5 h-3.5" />
                                                        {videoFile.name} ({(videoFile.size / (1024 * 1024)).toFixed(1)} MB)
                                                    </span>
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {/* Custom Thumbnail Options */}
                                <div className="pt-4 border-t border-gray-100">
                                    <div className="flex items-center justify-between mb-2">
                                        <label className="block text-xs font-bold text-gray-700 flex items-center gap-2">
                                            <ImageIcon className="w-4 h-4 text-indigo-500" />
                                            Video Poster Thumbnail
                                        </label>
                                        {isAutoGeneratedThumb && (
                                            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-100">
                                                <Sparkles className="w-3 h-3" /> Auto-Generated
                                            </span>
                                        )}
                                    </div>

                                    <div className="flex flex-col sm:flex-row gap-6 items-start">
                                        <div className="w-48 h-32 bg-gray-50 border-2 border-dashed border-gray-200 rounded-2xl flex items-center justify-center relative overflow-hidden group shrink-0">
                                            {thumbnailPreviewUrl ? (
                                                <>
                                                    <img
                                                        src={getMediaUrl(thumbnailPreviewUrl)}
                                                        alt="Video Poster Thumbnail"
                                                        className="w-full h-full object-cover"
                                                    />
                                                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                                        <label className="cursor-pointer bg-white text-gray-900 px-3 py-1.5 rounded-lg text-xs font-bold shadow-lg">
                                                            Change
                                                            <input type="file" className="hidden" onChange={handleThumbnailFileChange} accept="image/*" />
                                                        </label>
                                                    </div>
                                                </>
                                            ) : (
                                                <div className="text-center p-3">
                                                    <ImageIcon className="w-7 h-7 text-gray-300 mx-auto mb-1" />
                                                    <p className="text-[10px] text-gray-400 font-medium">No Thumbnail</p>
                                                </div>
                                            )}
                                        </div>

                                        <div className="space-y-2">
                                            <label className="inline-flex items-center px-4 py-2 bg-white border border-gray-200 rounded-xl text-xs font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-all cursor-pointer shadow-sm">
                                                <Upload className="w-3.5 h-3.5 mr-2 text-indigo-600" />
                                                {thumbnailPreviewUrl ? 'Upload Custom Graphic' : 'Select Custom Thumbnail'}
                                                <input
                                                    type="file"
                                                    className="hidden"
                                                    onChange={handleThumbnailFileChange}
                                                    accept="image/*"
                                                />
                                            </label>
                                            <p className="text-xs text-gray-400 leading-relaxed">
                                                You can upload a custom banner graphic or click <strong>"Capture Frame"</strong> on the video player above.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Action Bar */}
                            <div className="px-8 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-indigo-700 flex items-center gap-1.5">
                                    <AlertCircle className="w-4 h-4" /> Updates Hero section video player instantly.
                                </span>
                                <button
                                    type="submit"
                                    disabled={savingSection === 'video'}
                                    className="inline-flex items-center px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl shadow-md shadow-indigo-200 transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                                >
                                    {savingSection === 'video' ? (
                                        <>
                                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                            Saving Video...
                                        </>
                                    ) : (
                                        <>
                                            <Save className="w-4 h-4 mr-2" />
                                            Save Video Settings
                                        </>
                                    )}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* ── TAB 3: PHOTO ALBUM & GALLERY SUB-MENU ───────────────────────── */}
            {/* ─────────────────────────────────────────────────────────────────── */}
            {activeTab === 'album' && (
                <div className="max-w-4xl space-y-6 animate-in fade-in duration-200">
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                        <div className="bg-linear-to-r from-emerald-50 to-teal-50 px-6 py-4 border-b border-emerald-100 flex items-center justify-between">
                            <div className="flex items-center">
                                <Images className="w-5 h-5 text-emerald-600 mr-3" />
                                <div>
                                    <h2 className="text-base font-bold text-gray-800">Campus Photo Album & Gallery</h2>
                                    <p className="text-xs text-gray-500">Displayed in the About Section on the public homepage with interactive Canvas viewer</p>
                                </div>
                            </div>
                            <span className="text-xs text-emerald-700 font-bold bg-white px-2.5 py-1 rounded-lg border border-emerald-200">
                                {albumPhotos.length} Photos ({albumPhotos.filter((p) => p.is_active).length} Active)
                            </span>
                        </div>

                        <div className="p-6 sm:p-8 space-y-8">
                            {/* 1. Album Section Title & Subtext Settings */}
                            <form onSubmit={handleSaveAlbumSettings} className="space-y-4 pb-6 border-b border-gray-100">
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-xs font-bold text-gray-700 mb-2">
                                            Album Card Heading
                                        </label>
                                        <input
                                            type="text"
                                            value={albumHeading}
                                            onChange={(e) => setAlbumHeading(e.target.value)}
                                            placeholder="Campus & Event Gallery"
                                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:bg-white focus:border-transparent transition-all outline-none text-sm text-gray-800"
                                        />
                                    </div>

                                    <div>
                                        <label className="block text-xs font-bold text-gray-700 mb-2">
                                            Album Card Subtext
                                        </label>
                                        <input
                                            type="text"
                                            value={albumSubtext}
                                            onChange={(e) => setAlbumSubtext(e.target.value)}
                                            placeholder="Explore our vibrant campus life, workshops, and student achievements"
                                            className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:bg-white focus:border-transparent transition-all outline-none text-sm text-gray-800"
                                        />
                                    </div>
                                </div>

                                <div className="flex justify-end">
                                    <button
                                        type="submit"
                                        disabled={savingSection === 'album'}
                                        className="inline-flex items-center px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl shadow-sm transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                                    >
                                        {savingSection === 'album' ? (
                                            <>
                                                <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
                                                Saving...
                                            </>
                                        ) : (
                                            <>
                                                <Save className="w-3.5 h-3.5 mr-1.5" />
                                                Save Album Titles
                                            </>
                                        )}
                                    </button>
                                </div>
                            </form>

                            {/* 2. Upload New Photos Dropzone */}
                            <div className="bg-emerald-50/40 rounded-2xl p-6 border-2 border-dashed border-emerald-200 space-y-4">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                                    <div>
                                        <h3 className="text-sm font-bold text-emerald-950 flex items-center gap-2">
                                            <Plus className="w-4 h-4 text-emerald-600" />
                                            Upload Photos to Album
                                        </h3>
                                        <p className="text-xs text-emerald-800/80 mt-0.5">
                                            Select single or multiple high-resolution photos (JPG, PNG, WEBP).
                                        </p>
                                    </div>

                                    <label className="inline-flex items-center px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold transition-all shadow-sm cursor-pointer shrink-0">
                                        <Upload className="w-3.5 h-3.5 mr-2" />
                                        Select Images
                                        <input
                                            type="file"
                                            multiple
                                            accept="image/*"
                                            className="hidden"
                                            onChange={handleFileSelect}
                                        />
                                    </label>
                                </div>

                                {/* Selected Files Drawer */}
                                {selectedUploadFiles.length > 0 && (
                                    <div className="space-y-4 pt-4 border-t border-emerald-200/60 animate-in fade-in">
                                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                            <div>
                                                <label className="block text-xs font-bold text-gray-700 mb-1">
                                                    Title Prefix (Optional)
                                                </label>
                                                <input
                                                    type="text"
                                                    value={uploadTitlePrefix}
                                                    onChange={(e) => setUploadTitlePrefix(e.target.value)}
                                                    placeholder="e.g., Computer Lab Session"
                                                    className="w-full px-3 py-2 bg-white border border-gray-200 rounded-lg text-xs outline-none focus:ring-2 focus:ring-emerald-500"
                                                />
                                            </div>
                                            <div>
                                                <label className="block text-xs font-bold text-gray-700 mb-1">
                                                    Description / Caption (Optional)
                                                </label>
                                                <input
                                                    type="text"
                                                    value={uploadCaption}
                                                    onChange={(e) => setUploadCaption(e.target.value)}
                                                    placeholder="e.g., Hands-on practical class"
                                                    className="w-full px-3 py-2 bg-white border border-gray-200 rounded-lg text-xs outline-none focus:ring-2 focus:ring-emerald-500"
                                                />
                                            </div>
                                        </div>

                                        {/* Preview Thumbnails */}
                                        <div className="flex flex-wrap gap-3 max-h-44 overflow-y-auto p-1">
                                            {selectedUploadFiles.map((file, idx) => (
                                                <div
                                                    key={idx}
                                                    className="relative w-20 h-20 rounded-xl overflow-hidden border-2 border-emerald-300 group shadow-sm bg-white shrink-0"
                                                >
                                                    <img
                                                        src={URL.createObjectURL(file)}
                                                        alt={file.name}
                                                        className="w-full h-full object-cover"
                                                    />
                                                    <button
                                                        type="button"
                                                        onClick={() => handleRemoveSelectedFile(idx)}
                                                        title="Remove"
                                                        className="absolute top-1 right-1 w-5 h-5 rounded-full bg-black/70 text-white flex items-center justify-center hover:bg-red-600 transition-colors cursor-pointer"
                                                    >
                                                        <X className="w-3 h-3" />
                                                    </button>
                                                    <span className="absolute bottom-0 inset-x-0 bg-black/60 text-white text-[9px] truncate px-1 text-center">
                                                        {(file.size / 1024).toFixed(0)} KB
                                                    </span>
                                                </div>
                                            ))}
                                        </div>

                                        <div className="flex items-center justify-between pt-2">
                                            <span className="text-xs font-semibold text-emerald-800">
                                                {selectedUploadFiles.length} photo(s) selected
                                            </span>
                                            <div className="flex items-center gap-2">
                                                <button
                                                    type="button"
                                                    onClick={() => setSelectedUploadFiles([])}
                                                    className="px-3 py-1.5 text-xs text-gray-600 hover:text-gray-900 bg-white border border-gray-200 rounded-lg cursor-pointer"
                                                >
                                                    Clear
                                                </button>
                                                <button
                                                    type="button"
                                                    onClick={handleBatchUpload}
                                                    disabled={isUploadingPhotos}
                                                    className="inline-flex items-center px-4 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-lg shadow-sm transition-all disabled:opacity-50 cursor-pointer"
                                                >
                                                    {isUploadingPhotos ? (
                                                        <>
                                                            <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
                                                            Uploading...
                                                        </>
                                                    ) : (
                                                        <>
                                                            <Upload className="w-3.5 h-3.5 mr-1.5" />
                                                            Upload {selectedUploadFiles.length} Photo(s)
                                                        </>
                                                    )}
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* 3. Photos List & Sequence Manager */}
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <h3 className="text-sm font-bold text-gray-900">
                                        Current Album Photos ({albumPhotos.length})
                                    </h3>
                                    <p className="text-xs text-gray-400">
                                        Use arrows to reorder. Photos appear on the About section in this sequence.
                                    </p>
                                </div>

                                {loadingPhotos ? (
                                    <div className="py-8 text-center text-gray-400">
                                        <Loader2 className="w-6 h-6 animate-spin mx-auto mb-2 text-emerald-600" />
                                        <p className="text-xs">Loading album photos...</p>
                                    </div>
                                ) : albumPhotos.length === 0 ? (
                                    <div className="bg-gray-50 border border-gray-100 rounded-2xl p-8 text-center space-y-3">
                                        <Images className="w-10 h-10 text-gray-300 mx-auto" />
                                        <p className="text-sm font-bold text-gray-700">No Photos Uploaded Yet</p>
                                        <p className="text-xs text-gray-400 max-w-md mx-auto">
                                            Upload your photos above to feature them on the homepage album and fullscreen canvas viewer!
                                        </p>
                                    </div>
                                ) : (
                                    <div className="grid grid-cols-1 gap-3">
                                        {albumPhotos.map((photo, idx) => (
                                            <div
                                                key={photo.id}
                                                className={`p-4 bg-white rounded-xl border transition-all duration-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 ${photo.is_active
                                                    ? 'border-gray-200 hover:border-emerald-300 shadow-xs'
                                                    : 'border-dashed border-gray-300 bg-gray-50/70 opacity-70'
                                                    }`}
                                            >
                                                {/* Thumbnail & Title/Caption Info */}
                                                <div className="flex items-center gap-4 min-w-0 flex-1">
                                                    <div className="relative w-20 h-16 rounded-lg overflow-hidden bg-gray-100 shrink-0 border border-gray-200">
                                                        <img
                                                            src={getMediaUrl(photo.image)}
                                                            alt={photo.title || `Photo ${idx + 1}`}
                                                            className="w-full h-full object-cover"
                                                        />
                                                        <span className="absolute top-1 left-1 px-1.5 py-0.5 bg-black/70 text-white rounded text-[10px] font-bold">
                                                            #{idx + 1}
                                                        </span>
                                                    </div>

                                                    {editingPhotoId === photo.id ? (
                                                        <div className="flex-1 space-y-2 pr-2">
                                                            <input
                                                                type="text"
                                                                value={editTitle}
                                                                onChange={(e) => setEditTitle(e.target.value)}
                                                                placeholder="Photo Title"
                                                                className="w-full px-2.5 py-1 text-xs bg-gray-50 border border-gray-300 rounded-lg outline-none focus:ring-1 focus:ring-emerald-500 font-semibold"
                                                            />
                                                            <input
                                                                type="text"
                                                                value={editCaption}
                                                                onChange={(e) => setEditCaption(e.target.value)}
                                                                placeholder="Photo Caption"
                                                                className="w-full px-2.5 py-1 text-xs bg-gray-50 border border-gray-300 rounded-lg outline-none focus:ring-1 focus:ring-emerald-500 text-gray-600"
                                                            />
                                                        </div>
                                                    ) : (
                                                        <div className="min-w-0 flex-1">
                                                            <div className="flex items-center gap-2">
                                                                <h4 className="font-bold text-sm text-gray-900 truncate">
                                                                    {photo.title || `Photo #${idx + 1}`}
                                                                </h4>
                                                                {!photo.is_active && (
                                                                    <span className="px-2 py-0.5 text-[10px] font-bold bg-amber-50 text-amber-700 border border-amber-200 rounded-md">
                                                                        Hidden
                                                                    </span>
                                                                )}
                                                            </div>
                                                            <p className="text-xs text-gray-500 truncate mt-0.5">
                                                                {photo.caption || 'No caption provided'}
                                                            </p>
                                                        </div>
                                                    )}
                                                </div>

                                                {/* Action Buttons */}
                                                <div className="flex items-center gap-1.5 shrink-0 self-end sm:self-center">
                                                    {editingPhotoId === photo.id ? (
                                                        <>
                                                            <button
                                                                type="button"
                                                                onClick={() => handleSaveEdit(photo.id)}
                                                                title="Save Changes"
                                                                className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-700 hover:bg-emerald-600 hover:text-white flex items-center justify-center transition-colors cursor-pointer"
                                                            >
                                                                <Check className="w-4 h-4" />
                                                            </button>
                                                            <button
                                                                type="button"
                                                                onClick={() => setEditingPhotoId(null)}
                                                                title="Cancel"
                                                                className="w-8 h-8 rounded-lg bg-gray-100 text-gray-600 hover:bg-gray-200 flex items-center justify-center transition-colors cursor-pointer"
                                                            >
                                                                <X className="w-4 h-4" />
                                                            </button>
                                                        </>
                                                    ) : (
                                                        <button
                                                            type="button"
                                                            onClick={() => handleStartEdit(photo)}
                                                            title="Edit Title & Caption"
                                                            className="w-8 h-8 rounded-lg bg-gray-50 hover:bg-gray-100 text-gray-600 flex items-center justify-center transition-colors cursor-pointer"
                                                        >
                                                            <Edit3 className="w-3.5 h-3.5" />
                                                        </button>
                                                    )}

                                                    {/* Visibility Toggle */}
                                                    <button
                                                        type="button"
                                                        onClick={() => handleTogglePhotoVisibility(photo)}
                                                        title={photo.is_active ? 'Hide from Homepage' : 'Show on Homepage'}
                                                        className={`w-8 h-8 rounded-lg flex items-center justify-center transition-colors cursor-pointer ${photo.is_active
                                                            ? 'bg-emerald-50 text-emerald-700 hover:bg-emerald-100'
                                                            : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
                                                            }`}
                                                    >
                                                        {photo.is_active ? (
                                                            <Eye className="w-4 h-4" />
                                                        ) : (
                                                            <EyeOff className="w-4 h-4" />
                                                        )}
                                                    </button>

                                                    {/* Reorder Up */}
                                                    <button
                                                        type="button"
                                                        disabled={idx === 0}
                                                        onClick={() => handleMovePhoto(idx, 'up')}
                                                        title="Move Up"
                                                        className="w-8 h-8 rounded-lg bg-gray-50 hover:bg-gray-100 text-gray-600 disabled:opacity-30 disabled:cursor-not-allowed flex items-center justify-center transition-colors cursor-pointer"
                                                    >
                                                        <ArrowUp className="w-3.5 h-3.5" />
                                                    </button>

                                                    {/* Reorder Down */}
                                                    <button
                                                        type="button"
                                                        disabled={idx === albumPhotos.length - 1}
                                                        onClick={() => handleMovePhoto(idx, 'down')}
                                                        title="Move Down"
                                                        className="w-8 h-8 rounded-lg bg-gray-50 hover:bg-gray-100 text-gray-600 disabled:opacity-30 disabled:cursor-not-allowed flex items-center justify-center transition-colors cursor-pointer"
                                                    >
                                                        <ArrowDown className="w-3.5 h-3.5" />
                                                    </button>

                                                    {/* Delete Photo */}
                                                    <button
                                                        type="button"
                                                        onClick={() => handleDeletePhoto(photo.id)}
                                                        title="Delete Photo"
                                                        className="w-8 h-8 rounded-lg bg-red-50 hover:bg-red-600 hover:text-white text-red-600 flex items-center justify-center transition-colors cursor-pointer"
                                                    >
                                                        <Trash2 className="w-3.5 h-3.5" />
                                                    </button>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* ── TAB 4: PAYMENT DETAILS (BKASH) SUB-MENU ─────────────────────── */}
            {/* ─────────────────────────────────────────────────────────────────── */}
            {activeTab === 'payment' && (
                <div className="max-w-4xl space-y-6 animate-in fade-in duration-200">
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                        <div className="bg-pink-50 px-6 py-4 border-b border-pink-100 flex items-center justify-between">
                            <div className="flex items-center">
                                <QrCode className="w-5 h-5 text-[#D12053] mr-3" />
                                <div>
                                    <h2 className="text-base font-bold text-gray-800">bKash Payment Configuration</h2>
                                    <p className="text-xs text-gray-500">Merchant details shown on the checkout page for course purchases</p>
                                </div>
                            </div>
                            {settings?.updated_at && (
                                <span className="text-xs text-pink-600 font-medium bg-white px-2.5 py-1 rounded-lg border border-pink-100">
                                    Last Updated: {new Date(settings.updated_at).toLocaleDateString()}
                                </span>
                            )}
                        </div>

                        <form onSubmit={handleSaveBkash}>
                            <div className="p-6 sm:p-8 space-y-8">
                                {/* Merchant Number Input */}
                                <div className="max-w-md">
                                    <label className="block text-xs font-bold text-gray-700 mb-2 items-center gap-2">
                                        <Phone className="w-4 h-4 text-pink-500" />
                                        Merchant bKash Number
                                    </label>
                                    <div className="relative">
                                        <input
                                            type="text"
                                            value={merchantNumber}
                                            onChange={(e) => setMerchantNumber(e.target.value)}
                                            placeholder="e.g. 01XXXXXXXXX"
                                            className="w-full pl-4 pr-12 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-pink-500 focus:bg-white focus:border-transparent transition-all outline-none text-base font-mono tracking-wider"
                                        />
                                        <div className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400">
                                            <CheckCircle2 className="w-5 h-5 text-green-500" />
                                        </div>
                                    </div>
                                    <p className="text-xs text-gray-400 mt-2">
                                        This number is displayed to all students during manual or auto checkout.
                                    </p>
                                </div>

                                {/* QR Code Upload */}
                                <div>
                                    <label className="block text-xs font-bold text-gray-700 mb-3 items-center gap-2">
                                        <ImageIcon className="w-4 h-4 text-pink-500" />
                                        bKash QR Code Image
                                    </label>

                                    <div className="flex flex-col md:flex-row gap-8 items-start">
                                        {/* Preview Area */}
                                        <div className="w-48 h-48 bg-gray-50 border-2 border-dashed border-gray-200 rounded-2xl flex items-center justify-center relative overflow-hidden group">
                                            {qrCodePreview ? (
                                                <>
                                                    <img
                                                        src={getMediaUrl(qrCodePreview)}
                                                        alt="bKash QR Code"
                                                        className="w-full h-full object-contain p-2"
                                                    />
                                                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                                        <label className="cursor-pointer bg-white text-gray-900 px-3 py-1.5 rounded-lg text-xs font-bold shadow-lg">
                                                            Change Image
                                                            <input type="file" className="hidden" onChange={handleQrCodeChange} accept="image/*" />
                                                        </label>
                                                    </div>
                                                </>
                                            ) : (
                                                <div className="text-center p-4">
                                                    <Upload className="w-10 h-10 text-gray-300 mx-auto mb-2" />
                                                    <p className="text-[10px] text-gray-400 font-medium">No QR Code Uploaded</p>
                                                </div>
                                            )}
                                        </div>

                                        {/* Upload Instructions */}
                                        <div className="flex-1 space-y-4">
                                            <div className="bg-blue-50 p-4 rounded-xl border border-blue-100 flex items-start gap-3">
                                                <Info className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
                                                <div className="text-xs text-blue-800 space-y-1">
                                                    <p className="font-bold">Image Recommendations:</p>
                                                    <ul className="list-disc list-inside text-[11px] space-y-0.5 opacity-90">
                                                        <li>Square aspect ratio (1:1) is optimal</li>
                                                        <li>High-contrast bKash Merchant QR code</li>
                                                        <li>Max size: 2MB (JPG, PNG, WEBP)</li>
                                                    </ul>
                                                </div>
                                            </div>

                                            <label className="inline-flex items-center px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-xs font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-all cursor-pointer shadow-sm">
                                                <Upload className="w-4 h-4 mr-2 text-pink-600" />
                                                {qrCodePreview ? 'Upload New QR Code' : 'Select QR Code Image'}
                                                <input
                                                    type="file"
                                                    className="hidden"
                                                    onChange={handleQrCodeChange}
                                                    accept="image/*"
                                                />
                                            </label>
                                            {qrCodeFile && (
                                                <p className="text-xs text-green-600 font-medium flex items-center gap-1">
                                                    <CheckCircle2 className="w-3 h-3" />
                                                    Selected: {qrCodeFile.name}
                                                </p>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Card Footer */}
                            <div className="px-8 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-pink-700 flex items-center gap-1.5">
                                    <AlertCircle className="w-4 h-4" /> Merchant number and QR code appear on the checkout screen.
                                </span>
                                <button
                                    type="submit"
                                    disabled={savingSection === 'bkash'}
                                    className="inline-flex items-center px-5 py-2.5 bg-[#D12053] hover:bg-[#b01742] text-white font-bold rounded-xl shadow-md shadow-pink-200 transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                                >
                                    {savingSection === 'bkash' ? (
                                        <>
                                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                            Saving bKash...
                                        </>
                                    ) : (
                                        <>
                                            <Save className="w-4 h-4 mr-2" />
                                            Save bKash Settings
                                        </>
                                    )}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}

            {/* ─────────────────────────────────────────────────────────────────── */}
            {/* ── TAB 5: QUIZ & SMS NOTIFICATION SUB-MENU ─────────────────────── */}
            {/* ─────────────────────────────────────────────────────────────────── */}
            {activeTab === 'notifications' && (
                <div className="max-w-4xl space-y-6 animate-in fade-in duration-200">
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                        <div className="bg-violet-50 px-6 py-4 border-b border-violet-100 flex items-center justify-between">
                            <div className="flex items-center">
                                <Settings className="w-5 h-5 text-violet-600 mr-3" />
                                <div>
                                    <h2 className="text-base font-bold text-gray-800">Quiz & Notification Settings</h2>
                                    <p className="text-xs text-gray-500">Passing percentage threshold and Greenweb Bangladesh SMS token</p>
                                </div>
                            </div>
                        </div>

                        <form onSubmit={handleSaveQuiz}>
                            <div className="p-6 sm:p-8 space-y-6">
                                {/* Quiz Pass Percentage */}
                                <div className="max-w-md">
                                    <label className="block text-xs font-bold text-gray-700 mb-2">
                                        Quiz Passing Mark Threshold (%)
                                    </label>
                                    <div className="relative">
                                        <input
                                            type="number"
                                            min="0"
                                            max="100"
                                            step="1"
                                            value={quizPassPercentage}
                                            onChange={(e) => setQuizPassPercentage(Number(e.target.value))}
                                            placeholder="e.g. 50"
                                            className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:bg-white focus:border-transparent transition-all outline-none text-base font-bold"
                                        />
                                        <span className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">%</span>
                                    </div>
                                    <p className="text-xs text-gray-400 mt-2">
                                        Students scoring at or above this percentage will receive the Bangla "পাস" SMS. Scores below will receive the "ফেল" SMS.
                                    </p>
                                </div>

                                {/* Greenweb SMS Token */}
                                <div>
                                    <label className="block text-xs font-bold text-gray-700 mb-2">
                                        Greenweb BD SMS API Token
                                    </label>
                                    <input
                                        type="text"
                                        value={greenwebSmsToken}
                                        onChange={(e) => setGreenwebSmsToken(e.target.value)}
                                        placeholder="Enter your Greenweb SMS API Token (e.g., 1234567890abcdef)"
                                        className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:bg-white focus:border-transparent transition-all outline-none font-mono text-sm"
                                    />
                                    <p className="text-xs text-gray-400 mt-2">
                                        API token from Greenweb (http://api.greenweb.com.bd). If left empty, automated SMS logs are captured in mock mode.
                                    </p>
                                </div>
                            </div>

                            {/* Card Footer */}
                            <div className="px-8 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                                <span className="text-xs text-violet-700 flex items-center gap-1.5">
                                    <AlertCircle className="w-4 h-4" /> Controls automated student SMS dispatch and passing marks.
                                </span>
                                <button
                                    type="submit"
                                    disabled={savingSection === 'quiz'}
                                    className="inline-flex items-center px-5 py-2.5 bg-violet-600 hover:bg-violet-700 text-white font-bold rounded-xl shadow-md shadow-violet-200 transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                                >
                                    {savingSection === 'quiz' ? (
                                        <>
                                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                            Saving Quiz & SMS...
                                        </>
                                    ) : (
                                        <>
                                            <Save className="w-4 h-4 mr-2" />
                                            Save Quiz & SMS Settings
                                        </>
                                    )}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    )
}

export default SiteSettingsPage
