/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useEffect, useState, useRef } from 'react'
import {
    Settings,
    Save,
    QrCode,
    Phone,
    Upload,
    Image as ImageIcon,
    CheckCircle2,
    AlertCircle,
    Info,
    Video,
    Film,
    Play,
    Sparkles,
    Camera,
    Loader2,
} from 'lucide-react'
import { getSiteSettings, updateSiteSettings } from '../../../../lib/api'
import type { SiteSettings } from '../../../../types'
import Breadcrumb from '../../../components/Breadcrumb'
import { toast } from 'react-hot-toast'
import { isAxiosError } from 'axios'

type SavingSection = 'video' | 'bkash' | 'quiz' | null

const SiteSettingsPage: React.FC = () => {
    const [settings, setSettings] = useState<SiteSettings | null>(null)
    const [loading, setLoading] = useState(true)
    const [savingSection, setSavingSection] = useState<SavingSection>(null)

    // Form state - Homepage Video Tour
    const [videoHeading, setVideoHeading] = useState('')
    const [videoSubtext, setVideoSubtext] = useState('')
    const [videoFile, setVideoFile] = useState<File | null>(null)
    const [videoPreviewUrl, setVideoPreviewUrl] = useState<string | null>(null)
    const [thumbnailFile, setThumbnailFile] = useState<File | null>(null)
    const [thumbnailPreviewUrl, setThumbnailPreviewUrl] = useState<string | null>(null)
    const [isGeneratingThumbnail, setIsGeneratingThumbnail] = useState(false)
    const [isAutoGeneratedThumb, setIsAutoGeneratedThumb] = useState(false)

    // Form state - bKash
    const [merchantNumber, setMerchantNumber] = useState('')
    const [qrCodeFile, setQrCodeFile] = useState<File | null>(null)
    const [qrCodePreview, setQrCodePreview] = useState<string | null>(null)

    // Form state - Quiz & SMS
    const [quizPassPercentage, setQuizPassPercentage] = useState<number>(50)
    const [greenwebSmsToken, setGreenwebSmsToken] = useState('')

    const videoPreviewRef = useRef<HTMLVideoElement | null>(null)

    useEffect(() => {
        fetchSettings()
    }, [])

    const fetchSettings = async () => {
        try {
            const response = await getSiteSettings()
            if (response.data.success) {
                const data = response.data.data
                setSettings(data)
                // Video settings
                setVideoHeading(data.campus_tour_heading || '')
                setVideoSubtext(data.campus_tour_subtext || '')
                setVideoPreviewUrl(data.campus_tour_video || null)
                setThumbnailPreviewUrl(data.campus_tour_thumbnail || null)
                // bKash settings
                setMerchantNumber(data.bkash_merchant_number || '')
                setQrCodePreview(data.bkash_qr_code)
                // Quiz & SMS settings
                setQuizPassPercentage(data.quiz_pass_percentage ?? 50)
                setGreenwebSmsToken(data.greenweb_sms_token || '')
            }
        } catch (error: any) {
            toast.error(error.message || 'Failed to load settings')
        } finally {
            setLoading(false)
        }
    }

    const generateThumbnailFromVideo = (file: File): Promise<File> => {
        return new Promise((resolve, reject) => {
            const video = document.createElement('video')
            video.preload = 'auto'
            video.muted = true
            video.playsInline = true
            const objectUrl = URL.createObjectURL(file)
            video.src = objectUrl

            video.onloadeddata = () => {
                const seekTime = Math.min(1.0, video.duration > 1 ? 1.0 : video.duration / 2 || 0.1)
                video.currentTime = seekTime
            }

            video.onseeked = () => {
                try {
                    const canvas = document.createElement('canvas')
                    canvas.width = video.videoWidth || 1280
                    canvas.height = video.videoHeight || 720
                    const ctx = canvas.getContext('2d')
                    if (ctx) {
                        ctx.drawImage(video, 0, 0, canvas.width, canvas.height)
                        canvas.toBlob((blob) => {
                            URL.revokeObjectURL(objectUrl)
                            if (blob) {
                                const cleanName = file.name.replace(/\.[^/.]+$/, '')
                                const thumbFile = new File([blob], `thumb_${cleanName}.jpg`, {
                                    type: 'image/jpeg',
                                })
                                resolve(thumbFile)
                            } else {
                                reject(new Error('Failed to generate thumbnail blob'))
                            }
                        }, 'image/jpeg', 0.90)
                    } else {
                        URL.revokeObjectURL(objectUrl)
                        reject(new Error('Canvas 2D context not available'))
                    }
                } catch (err) {
                    URL.revokeObjectURL(objectUrl)
                    reject(err)
                }
            }

            video.onerror = (e) => {
                URL.revokeObjectURL(objectUrl)
                reject(e)
            }
        })
    }

    const handleCaptureCurrentFrame = () => {
        if (!videoPreviewRef.current) return
        const video = videoPreviewRef.current
        try {
            const canvas = document.createElement('canvas')
            canvas.width = video.videoWidth || 1280
            canvas.height = video.videoHeight || 720
            const ctx = canvas.getContext('2d')
            if (ctx) {
                ctx.drawImage(video, 0, 0, canvas.width, canvas.height)
                canvas.toBlob((blob) => {
                    if (blob) {
                        const thumbFile = new File([blob], `captured_frame_${Date.now()}.jpg`, {
                            type: 'image/jpeg',
                        })
                        setThumbnailFile(thumbFile)
                        setThumbnailPreviewUrl(URL.createObjectURL(thumbFile))
                        setIsAutoGeneratedThumb(true)
                        toast.success('Captured current video frame as thumbnail!')
                    }
                }, 'image/jpeg', 0.92)
            }
        } catch (err) {
            console.error('Frame capture error:', err)
            toast.error('Could not capture frame from current video')
        }
    }

    const handleVideoFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            if (file.size > 200 * 1024 * 1024) {
                toast.error('Video file size should not exceed 200MB')
                return
            }
            setVideoFile(file)
            setVideoPreviewUrl(URL.createObjectURL(file))

            // Automatically generate thumbnail from video
            setIsGeneratingThumbnail(true)
            try {
                const autoThumb = await generateThumbnailFromVideo(file)
                setThumbnailFile(autoThumb)
                setThumbnailPreviewUrl(URL.createObjectURL(autoThumb))
                setIsAutoGeneratedThumb(true)
                toast.success('Auto-generated video thumbnail from first frame!')
            } catch (err) {
                console.warn('Auto thumbnail generation warning:', err)
            } finally {
                setIsGeneratingThumbnail(false)
            }
        }
    }

    const handleThumbnailFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            setThumbnailFile(file)
            setIsAutoGeneratedThumb(false)
            const reader = new FileReader()
            reader.onloadend = () => {
                setThumbnailPreviewUrl(reader.result as string)
            }
            reader.readAsDataURL(file)
        }
    }

    const handleQrCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]
        if (file) {
            setQrCodeFile(file)
            const reader = new FileReader()
            reader.onloadend = () => {
                setQrCodePreview(reader.result as string)
            }
            reader.readAsDataURL(file)
        }
    }

    // ── Save Video Section ──────────────────────────────────────────────────
    const handleSaveVideo = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('video')

        try {
            const formData = new FormData()
            formData.append('campus_tour_heading', videoHeading)
            formData.append('campus_tour_subtext', videoSubtext)

            if (videoFile) {
                formData.append('campus_tour_video', videoFile)
            }
            if (thumbnailFile) {
                formData.append('campus_tour_thumbnail', thumbnailFile)
            }

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('Homepage video settings saved successfully!')
                const updated = response.data.data
                setSettings(updated)
                setVideoFile(null)
                setThumbnailFile(null)
                setVideoPreviewUrl(updated.campus_tour_video || null)
                setThumbnailPreviewUrl(updated.campus_tour_thumbnail || null)
                setIsAutoGeneratedThumb(false)
            }
        } catch (error) {
            let message = 'Failed to save video settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    // ── Save bKash Section ──────────────────────────────────────────────────
    const handleSaveBkash = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('bkash')

        try {
            const formData = new FormData()
            formData.append('bkash_merchant_number', merchantNumber)

            if (qrCodeFile) {
                formData.append('bkash_qr_code', qrCodeFile)
            }

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('bKash payment settings saved successfully!')
                const updated = response.data.data
                setSettings(updated)
                setQrCodeFile(null)
                setQrCodePreview(updated.bkash_qr_code)
            }
        } catch (error) {
            let message = 'Failed to save bKash settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    // ── Save Quiz & SMS Section ─────────────────────────────────────────────
    const handleSaveQuiz = async (e: React.FormEvent) => {
        e.preventDefault()
        setSavingSection('quiz')

        try {
            const formData = new FormData()
            formData.append('quiz_pass_percentage', quizPassPercentage.toString())
            formData.append('greenweb_sms_token', greenwebSmsToken)

            const response = await updateSiteSettings(formData)
            if (response.data.success) {
                toast.success('Quiz & SMS notification settings saved successfully!')
                const updated = response.data.data
                setSettings(updated)
            }
        } catch (error) {
            let message = 'Failed to save quiz settings'
            if (isAxiosError(error)) {
                message = error.response?.data?.error?.message || message
            }
            toast.error(message)
        } finally {
            setSavingSection(null)
        }
    }

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-100">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-violet-600"></div>
            </div>
        )
    }

    return (
        <div className="pb-10">
            <Breadcrumb
                name="Platform Settings"
                subtitle="Configure global payment details, homepage video, and site settings"
                icon={Settings}
            />

            <div className="mt-8 max-w-4xl space-y-6">

                {/* ── Component 1: Virtual Campus Tour Video Section ── */}
                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="bg-linear-to-r from-blue-50 to-indigo-50 px-6 py-4 border-b border-blue-100 flex items-center justify-between">
                        <div className="flex items-center">
                            <Video className="w-5 h-5 text-indigo-600 mr-3" />
                            <h2 className="text-lg font-bold text-gray-800">Homepage Video (Virtual Campus Tour)</h2>
                        </div>
                        <span className="text-xs text-indigo-600 font-semibold bg-white px-2.5 py-1 rounded-lg border border-indigo-100">
                            Homepage Section
                        </span>
                    </div>

                    <form onSubmit={handleSaveVideo}>
                        <div className="p-8 space-y-6">
                            {/* Heading & Subtext */}
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-bold text-gray-700 mb-2">
                                        Video Heading
                                    </label>
                                    <input
                                        type="text"
                                        value={videoHeading}
                                        onChange={(e) => setVideoHeading(e.target.value)}
                                        placeholder="Virtual Campus Tour"
                                        className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white focus:border-transparent transition-all outline-none text-sm text-gray-800"
                                    />
                                    <p className="text-xs text-gray-400 mt-1.5">
                                        Leave blank to use default: <strong>"Virtual Campus Tour"</strong>
                                    </p>
                                </div>

                                <div>
                                    <label className="block text-sm font-bold text-gray-700 mb-2">
                                        Video Subtext
                                    </label>
                                    <input
                                        type="text"
                                        value={videoSubtext}
                                        onChange={(e) => setVideoSubtext(e.target.value)}
                                        placeholder="Experience our state-of-the-art facilities"
                                        className="w-full px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:bg-white focus:border-transparent transition-all outline-none text-sm text-gray-800"
                                    />
                                    <p className="text-xs text-gray-400 mt-1.5">
                                        Leave blank to use default: <strong>"Experience our state-of-the-art facilities"</strong>
                                    </p>
                                </div>
                            </div>

                            {/* Video File Upload & Preview */}
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2 flex items-center gap-2">
                                    <Film className="w-4 h-4 text-indigo-500" />
                                    Campus Tour Video File (.mp4, .webm, .mov)
                                </label>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
                                    {/* Video Preview */}
                                    <div className="w-full h-52 bg-gray-900 rounded-2xl overflow-hidden relative flex flex-col items-center justify-center border border-gray-200 group">
                                        {videoPreviewUrl ? (
                                            <>
                                                <video
                                                    ref={videoPreviewRef}
                                                    src={videoPreviewUrl}
                                                    controls
                                                    className="w-full h-full object-contain"
                                                    poster={thumbnailPreviewUrl || undefined}
                                                />
                                                <button
                                                    type="button"
                                                    onClick={handleCaptureCurrentFrame}
                                                    title="Capture current paused video frame as thumbnail"
                                                    className="absolute top-3 right-3 px-2.5 py-1.5 bg-black/70 hover:bg-black/90 text-white rounded-lg text-xs font-semibold backdrop-blur-sm border border-white/20 transition-all flex items-center gap-1.5 cursor-pointer opacity-0 group-hover:opacity-100 z-10"
                                                >
                                                    <Camera className="w-3.5 h-3.5" /> Capture Frame
                                                </button>
                                            </>
                                        ) : (
                                            <div className="text-center p-4">
                                                <Play className="w-10 h-10 text-gray-600 mx-auto mb-2" />
                                                <p className="text-xs text-gray-400 font-medium">No Video Uploaded</p>
                                                <p className="text-[10px] text-gray-500 mt-0.5">Placeholder will be shown on homepage</p>
                                            </div>
                                        )}
                                    </div>

                                    {/* Video Upload Control */}
                                    <div className="space-y-3">
                                        <div className="bg-indigo-50/70 p-4 rounded-xl border border-indigo-100 text-xs text-indigo-900 space-y-1">
                                            <p className="font-bold flex items-center gap-1.5">
                                                <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                                                Auto-Thumbnail Generator:
                                            </p>
                                            <p className="text-[11px] opacity-90">
                                                When you select a video, a high-resolution thumbnail is automatically extracted from the video frame.
                                            </p>
                                        </div>

                                        <div className="flex flex-col gap-2">
                                            <label className="inline-flex items-center px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-xs font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-all cursor-pointer shadow-sm w-fit">
                                                <Upload className="w-3.5 h-3.5 mr-2 text-indigo-600" />
                                                {videoPreviewUrl ? 'Replace Video File' : 'Select Video File'}
                                                <input
                                                    type="file"
                                                    className="hidden"
                                                    onChange={handleVideoFileChange}
                                                    accept="video/*"
                                                />
                                            </label>

                                            {isGeneratingThumbnail && (
                                                <span className="text-xs text-indigo-600 font-medium flex items-center gap-1.5">
                                                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                                                    Generating video thumbnail...
                                                </span>
                                            )}

                                            {videoFile && (
                                                <span className="text-xs text-green-600 font-medium flex items-center gap-1">
                                                    <CheckCircle2 className="w-3.5 h-3.5" />
                                                    {videoFile.name} ({(videoFile.size / (1024 * 1024)).toFixed(1)} MB)
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Video Thumbnail Display & Preview */}
                            <div className="pt-4 border-t border-gray-100">
                                <div className="flex items-center justify-between mb-2">
                                    <label className="block text-sm font-bold text-gray-700 flex items-center gap-2">
                                        <ImageIcon className="w-4 h-4 text-indigo-500" />
                                        Video Thumbnail
                                    </label>
                                    {isAutoGeneratedThumb && (
                                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-100">
                                            <Sparkles className="w-3 h-3" /> Auto-Generated from Video
                                        </span>
                                    )}
                                </div>

                                <div className="flex flex-col sm:flex-row gap-6 items-start">
                                    <div className="w-48 h-32 bg-gray-50 border-2 border-dashed border-gray-200 rounded-2xl flex items-center justify-center relative overflow-hidden group shrink-0">
                                        {thumbnailPreviewUrl ? (
                                            <>
                                                <img
                                                    src={thumbnailPreviewUrl}
                                                    alt="Video Card Thumbnail"
                                                    className="w-full h-full object-cover"
                                                />
                                                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                                    <label className="cursor-pointer bg-white text-gray-900 px-3 py-1.5 rounded-lg text-xs font-bold shadow-lg">
                                                        Change
                                                        <input type="file" className="hidden" onChange={handleThumbnailFileChange} accept="image/*" />
                                                    </label>
                                                </div>
                                            </>
                                        ) : (
                                            <div className="text-center p-3">
                                                <ImageIcon className="w-7 h-7 text-gray-300 mx-auto mb-1" />
                                                <p className="text-[10px] text-gray-400 font-medium">No Thumbnail</p>
                                                <p className="text-[9px] text-gray-400">Uploads with video</p>
                                            </div>
                                        )}
                                    </div>

                                    <div className="space-y-2">
                                        <label className="inline-flex items-center px-4 py-2 bg-white border border-gray-200 rounded-xl text-xs font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-all cursor-pointer shadow-sm">
                                            <Upload className="w-3.5 h-3.5 mr-2 text-indigo-600" />
                                            {thumbnailPreviewUrl ? 'Upload Custom Image' : 'Select Custom Thumbnail'}
                                            <input
                                                type="file"
                                                className="hidden"
                                                onChange={handleThumbnailFileChange}
                                                accept="image/*"
                                            />
                                        </label>
                                        <p className="text-xs text-gray-400 leading-relaxed">
                                            Auto-extracted when uploading a video. You can also upload a custom graphic or pause the video and click <strong>"Capture Frame"</strong> above.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Card Footer: Save Button for Video */}
                        <div className="px-8 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                            <div className="flex items-center gap-2 text-indigo-700">
                                <AlertCircle className="w-4 h-4" />
                                <span className="text-xs font-medium">Video changes update the homepage card immediately.</span>
                            </div>
                            <button
                                type="submit"
                                disabled={savingSection === 'video'}
                                className="inline-flex items-center px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl shadow-md shadow-indigo-200 transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                            >
                                {savingSection === 'video' ? (
                                    <>
                                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                        Saving Video...
                                    </>
                                ) : (
                                    <>
                                        <Save className="w-4 h-4 mr-2" />
                                        Save Video Settings
                                    </>
                                )}
                            </button>
                        </div>
                    </form>
                </div>

                {/* ── Component 2: bKash Configuration Section ── */}
                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="bg-pink-50 px-6 py-4 border-b border-pink-100 flex items-center justify-between">
                        <div className="flex items-center">
                            <QrCode className="w-5 h-5 text-[#D12053] mr-3" />
                            <h2 className="text-lg font-bold text-gray-800">bKash Payment Details</h2>
                        </div>
                        {settings?.updated_at && (
                            <span className="text-xs text-pink-600 font-medium bg-white px-2 py-1 rounded-lg border border-pink-100">
                                Last Updated: {new Date(settings.updated_at).toLocaleDateString()}
                            </span>
                        )}
                    </div>

                    <form onSubmit={handleSaveBkash}>
                        <div className="p-8 space-y-8">
                            {/* Merchant Number Input */}
                            <div className="max-w-md">
                                <label className="block text-sm font-bold text-gray-700 mb-2 items-center gap-2">
                                    <Phone className="w-4 h-4 text-pink-500" />
                                    Merchant bKash Number
                                </label>
                                <div className="relative">
                                    <input
                                        type="text"
                                        value={merchantNumber}
                                        onChange={(e) => setMerchantNumber(e.target.value)}
                                        placeholder="e.g. 01XXXXXXXXX"
                                        className="w-full pl-4 pr-12 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-pink-500 focus:bg-white focus:border-transparent transition-all outline-none text-lg font-mono tracking-wider"
                                    />
                                    <div className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400">
                                        <CheckCircle2 className="w-5 h-5 text-green-500" />
                                    </div>
                                </div>
                                <p className="text-xs text-gray-400 mt-2">
                                    This number will be displayed to all students on the checkout page.
                                </p>
                            </div>

                            {/* QR Code Upload */}
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-4 items-center gap-2">
                                    <ImageIcon className="w-4 h-4 text-pink-500" />
                                    bKash QR Code Image
                                </label>

                                <div className="flex flex-col md:flex-row gap-8 items-start">
                                    {/* Preview Area */}
                                    <div className="w-48 h-48 bg-gray-50 border-2 border-dashed border-gray-200 rounded-2xl flex items-center justify-center relative overflow-hidden group">
                                        {qrCodePreview ? (
                                            <>
                                                <img
                                                    src={qrCodePreview}
                                                    alt="bKash QR Code"
                                                    className="w-full h-full object-contain p-2"
                                                />
                                                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                                    <label className="cursor-pointer bg-white text-gray-900 px-3 py-1.5 rounded-lg text-xs font-bold shadow-lg">
                                                        Change Image
                                                        <input type="file" className="hidden" onChange={handleQrCodeChange} accept="image/*" />
                                                    </label>
                                                </div>
                                            </>
                                        ) : (
                                            <div className="text-center p-4">
                                                <Upload className="w-10 h-10 text-gray-300 mx-auto mb-2" />
                                                <p className="text-[10px] text-gray-400 font-medium">No QR Code Uploaded</p>
                                            </div>
                                        )}
                                    </div>

                                    {/* Upload Instructions */}
                                    <div className="flex-1 space-y-4">
                                        <div className="bg-blue-50 p-4 rounded-xl border border-blue-100 flex items-start gap-3">
                                            <Info className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
                                            <div className="text-sm text-blue-800 space-y-1">
                                                <p className="font-bold">Image Recommendations:</p>
                                                <ul className="list-disc list-inside text-xs space-y-1 opacity-80">
                                                    <li>Square aspect ratio (1:1) is best</li>
                                                    <li>Clear, high-contrast QR code</li>
                                                    <li>Max size: 2MB (JPG, PNG, WEBP)</li>
                                                </ul>
                                            </div>
                                        </div>

                                        <label className="inline-flex items-center px-4 py-2.5 bg-white border border-gray-200 rounded-xl text-sm font-bold text-gray-700 hover:bg-gray-50 hover:border-gray-300 transition-all cursor-pointer shadow-sm">
                                            <Upload className="w-4 h-4 mr-2 text-pink-600" />
                                            {qrCodePreview ? 'Upload New QR Code' : 'Select QR Code Image'}
                                            <input
                                                type="file"
                                                className="hidden"
                                                onChange={handleQrCodeChange}
                                                accept="image/*"
                                            />
                                        </label>
                                        {qrCodeFile && (
                                            <p className="text-xs text-green-600 font-medium flex items-center gap-1">
                                                <CheckCircle2 className="w-3 h-3" />
                                                Selected: {qrCodeFile.name}
                                            </p>
                                        )}
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Card Footer: Save Button for bKash */}
                        <div className="px-8 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                            <div className="flex items-center gap-2 text-pink-700">
                                <AlertCircle className="w-4 h-4" />
                                <span className="text-xs font-medium">Merchant number and QR code are visible on checkout.</span>
                            </div>
                            <button
                                type="submit"
                                disabled={savingSection === 'bkash'}
                                className="inline-flex items-center px-5 py-2.5 bg-[#D12053] hover:bg-[#b01742] text-white font-bold rounded-xl shadow-md shadow-pink-200 transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                            >
                                {savingSection === 'bkash' ? (
                                    <>
                                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                        Saving bKash...
                                    </>
                                ) : (
                                    <>
                                        <Save className="w-4 h-4 mr-2" />
                                        Save bKash Settings
                                    </>
                                )}
                            </button>
                        </div>
                    </form>
                </div>

                {/* ── Component 3: Notification & Quiz Settings Section ── */}
                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="bg-violet-50 px-6 py-4 border-b border-violet-100 flex items-center justify-between">
                        <div className="flex items-center">
                            <Settings className="w-5 h-5 text-violet-600 mr-3" />
                            <h2 className="text-lg font-bold text-gray-800">Quiz & Notification Settings</h2>
                        </div>
                    </div>

                    <form onSubmit={handleSaveQuiz}>
                        <div className="p-8 space-y-6">
                            {/* Quiz Pass Percentage */}
                            <div className="max-w-md">
                                <label className="block text-sm font-bold text-gray-700 mb-2">
                                    Quiz Passing Mark Percentage (%)
                                </label>
                                <div className="relative">
                                    <input
                                        type="number"
                                        min="0"
                                        max="100"
                                        step="1"
                                        value={quizPassPercentage}
                                        onChange={(e) => setQuizPassPercentage(Number(e.target.value))}
                                        placeholder="e.g. 50"
                                        className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:bg-white focus:border-transparent transition-all outline-none text-lg font-bold"
                                    />
                                    <span className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 font-bold">%</span>
                                </div>
                                <p className="text-xs text-gray-400 mt-2">
                                    Students scoring at or above this percentage will receive the Bangla "পাস" SMS. Scores below will receive the "ফেল" SMS.
                                </p>
                            </div>

                            {/* Greenweb SMS Token */}
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">
                                    Greenweb BD SMS API Token
                                </label>
                                <input
                                    type="text"
                                    value={greenwebSmsToken}
                                    onChange={(e) => setGreenwebSmsToken(e.target.value)}
                                    placeholder="Enter your Greenweb SMS API Token (e.g., 1234567890abcdef)"
                                    className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:bg-white focus:border-transparent transition-all outline-none font-mono text-sm"
                                />
                                <p className="text-xs text-gray-400 mt-2">
                                    API token from Greenweb (http://api.greenweb.com.bd). If left empty, SMS logs will be recorded in mock mode.
                                </p>
                            </div>
                        </div>

                        {/* Card Footer: Save Button for Quiz & SMS */}
                        <div className="px-8 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                            <div className="flex items-center gap-2 text-violet-700">
                                <AlertCircle className="w-4 h-4" />
                                <span className="text-xs font-medium">Controls automated SMS dispatch and quiz pass/fail marks.</span>
                            </div>
                            <button
                                type="submit"
                                disabled={savingSection === 'quiz'}
                                className="inline-flex items-center px-5 py-2.5 bg-violet-600 hover:bg-violet-700 text-white font-bold rounded-xl shadow-md shadow-violet-200 transition-all active:scale-95 disabled:opacity-50 cursor-pointer text-xs"
                            >
                                {savingSection === 'quiz' ? (
                                    <>
                                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                                        Saving Quiz & SMS...
                                    </>
                                ) : (
                                    <>
                                        <Save className="w-4 h-4 mr-2" />
                                        Save Quiz & SMS Settings
                                    </>
                                )}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    )
}

export default SiteSettingsPage
