# Generated by Django 4.2.9 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_number',
            field=models.CharField(blank=True, help_text='The phone number the student used to send the payment (e.g., bKash number)', max_length=20, null=True),
        ),
    ]
