# Generated by Django 4.2.9 on 2026-08-28 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_quizsubmission_student_answers'),
        ('payments', '0002_payment_sender_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10.0 for 10%, 50.0 for 50%)', max_digits=5)),
                ('valid_from', models.DateTimeField(help_text='Start date/time of validity')),
                ('valid_until', models.DateTimeField(help_text='Expiration date/time')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions allowed (leave blank for unlimited)', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, help_text='Total number of times used')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable promo code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Select courses eligible for this promo code (leave blank to apply to all courses)', related_name='promo_codes', to='courses.course')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
